# **Getting Started with Python**


We'll be using Jupyter Notebook for our programming sessions. It supports many programming languages, we need Python installed before installing Jupyter Notebook. UNIX based system like Mac and Linux have python preinstalled, for windows you can download and install python from [here](https://www.python.org/downloads/).  
Alternatively you can install Anaconda (it has packages we need) from [here](https://www.anaconda.com/products/individual).  
Download the installer according to your OS. If you're not familiar with command line installation then choose the Graphical installer.   
Via Anaconda navigator you can get multiple IDEs like Jupyter Notebook, Spyder, Visual Studio, etc. There are many options to use, it is completely a personal choice which you can explore.  


---
## Environments

### Windows
- Install Anaconda > Launch Anaconda Navigator and launch Jupyter Notebook
- Alternatively Open command prompt (Press Windows and type 'cmd')  
Enter the following command to run  
```
jupyter notebook
```

### MacOS
- Install Anaconda > Launch Anaconda Navigator and launch Jupyter Notebook
- Alternatively open Terminal and enter following command  
```
jupyter notebook
```

### Linux
- Install Anaconda > [see detailed instructions for Linux](https://docs.anaconda.com/anaconda/install/linux/)
- Open terminal (CTRL + ALT + T) and enter following command  
```
jupyter notebook
```


---

## .py and .ipynb formats 
- .py is a regular python file. It's plain text and contains just your code.

- .ipynb is a python notebook (Jupyter Notebook) and it contains the notebook code, the execution results and other internal settings in a specific format. You can just run .ipynb on the jupyter environment.

## **Jupyter Notebook Essentials**

Jupyter Notebooks are interactive tools combining **code**, **output**, and **documentation**. Here are some key essentials to get started:

### **Running a Cell**
- `Shift + Enter` → **Run** the cell and move to the next.  
- `Ctrl + Enter` → **Run** the cell and stay on the current cell.  

### **Cell Types**
There are 3 basic cell types:
- **Code cells:** For writing and executing Python code.
- **Markdown cells:** For adding text, explanations, equations, and images. (Markup language/HTML). When a Markdown cell is executed, the markdown code is converted into the corresponding formatted rich text. Within Markdown cells, you can also include $mathematics$ in a straightforward way using standard $\LaTeX$ notation: `$...$` for inline mathematics and `$$...$$` for displayed mathematics. The $\LaTeX$ portions are automatically rendered in the HTML output as equations with high quality typography. This is made possible by [MathJax](https://www.mathjax.org/), which supports a large subset of $\LaTeX$ functionality.
- **Raw cells:** Unformatted text that is included, without modifications, when notebooks are converted to different formats using nbconvert. 

### **Useful Shortcuts**
- **Create a new cell**:  
    - `A` → Insert a cell **above**.  
    - `B` → Insert a cell **below**.  
- **Delete a cell**: Press `D` **twice** (`D, D`).  
- **Save notebook**: `S` or `Ctrl + S`.  
- **Change cell type**:  
    - Code → Press `Y`.  
    - Markdown → Press `M`.


---
## Using Google Colab
- [Google Colab](https://colab.research.google.com/) is very similar to Jupyter Notebook. It has same types of cell blocks and markdown text blocks and supports everthing that can be done in jupyter.  
- Added benifit is the cloud sync, you can access your code files on any device by logging into your google account as the colab files are stored on google drive. Colab opens in browser window just like Jupyter but it uses Python 3 Google Compute Engine Backend instead of IPython kernel in Jupyter, so you need internet connectivity.
- There is option to connect to local runtime so that you can use colab offline but you have to [follow this procedure](https://research.google.com/colaboratory/local-runtimes.html) to make it happen.  
- Rest all the instructions are same as Jupyter Notebook. [Here's a Cheat sheet for Google Colab](https://github.com/Tanu-N-Prabhu/Python/blob/master/Cheat_sheet_for_Google_Colab.ipynb).

# Basics

In [1]:
# This is a comment. '#' is used for comments which can fit in one line

'''Text enclosed in three single quotes
allows to write multi line comments'''

'Text enclosed in three single quotes\nallows to write multi line comments'

In [2]:
print('Hello World')

Hello World


In [3]:
print("Hubble's Law")

Hubble's Law


In [4]:
print('Hubble\'s Law')

Hubble's Law


In [5]:
a = 3
b = 4
c = a+b

In [6]:
print(c)

7


In [7]:
c

7

### Operations

| Python Operator | Description  |
| :---: | :---: |
| `+` | addition |
| `-` | subtraction |
| `*` | multiplication |
| `/` | division |
| `**` | power |

## There are different object types in Python

- Strings
- Numbers
- Lists
- Tuples
- Dictionaries
- Set
- Boolean

## Strings

In [8]:
s = "Simple string. A sequence of characters which can also be numbers 1,2,3 and special characters `/@#$% "

In [9]:
s

'Simple string. A sequence of characters which can also be numbers 1,2,3 and special characters `/@#$% '

In [10]:
# Using escape characters and line change or tab operators in print statement

message = "This is the first day of Astro winter school.\nOrganiser:\tWilson College\nLanguage:\tPython"

In [11]:
print(message)

This is the first day of Astro winter school.
Organiser:	Wilson College
Language:	Python


#### Formatted string

Used to parse a variable while printing string

In [12]:
duration = 7
message = f"The Astro winter school will be for {duration} days."

In [13]:
print(message)

The Astro winter school will be for 7 days.


In [14]:
message

'The Astro winter school will be for 7 days.'

In [15]:
message[5:]

'stro winter school will be for 7 days.'

In [16]:
message[:7]

'The Ast'

## Numbers
There are 3 numeric types:

- `int`
- `float`
- `complex`

#### How to differentiate between types of numbers?

There is a small note regarding the inspection of different number types.

"*How do we know what type of number is in your code?*"

To solve this issue there is an in-built function called `type()` which lets you know the type of an object.



In [17]:
# If you are given a string which includes a number, such as:
a = '24'
print(type(a)) #Output: <class 'str'>

# Converting string type to integer type:
b = int(a)
print(type(b)) #Output: <class 'int'>

<class 'str'>
<class 'int'>


### Floating numbers

Floating numbers are used when we want to play around with numbers with decimal numbers.
For example, `e = 2.718`.

You can convert a string to a floating number, for example:

In [18]:
e_string = '2.718'

e_float = float(e_string)

print(f"{e_float}\n Type:{type(e_float)}")

2.718
 Type:<class 'float'>


- If you need to **round-off** the floating number use the method `round()` as follows:

In [19]:
a = 4.54578

# rounding off to three decimal places.
round(a, 3)

4.546

### Imaginary numbers:

**Defining an imaginary number**:

Main ways to define the complex number:

In [20]:
c = 5 + 4j
print(type(c))

d = 10j + 7
print(type(d))

f = 2j
print(type(f))

<class 'complex'>
<class 'complex'>
<class 'complex'>


Python understands "`j`" as $\sqrt{-1}$

Common mistakes to avoid:

- Don't use `a + b*j`, otherwise you will encounter an error. Instead use the above methods to define the complex number.

<u>**Note**</u>: If we want to define a *very large or a very small number*, for example, the planck's constant,  *h* = $6.626*10^{-34}$ (in SI Units), or speed of light, *c* = $3*10^{8}$ (SI Units). We can use the following notation:

In [21]:
# Planck's constant
h = 6.626e-34
print(h)
# Speed of light
c = 3e8
print(c)

6.626e-34
300000000.0


## Tuples

Tuples are used for storing multiple items in a single variable.
The items can be stored inside the curvy braces "`()`".



In [22]:
t1 = (1,3,5,7,9)

t2 = ('one','three', 'five', 'seven', 'nine')

t3 = ('one', 3, 'five', 7, 'nine')

print(f"{t1}\n{t2}\n{t3}")

(1, 3, 5, 7, 9)
('one', 'three', 'five', 'seven', 'nine')
('one', 3, 'five', 7, 'nine')


Above are all examples of Tuples.

 A 'list' is very much similar to a tuple. The only **difference between a tuple and a list** is that a tuple's value cannot be changed after defining it. We shall learn about lists and its importance in the coming sections.

You can check the **length of the tuple** simply by using `len()` method.




In [23]:
len(t1)

5

In [24]:
len(t1)

5

## Dictionary

A **dictionary** in Python is a collection of key-value pairs. It is used to store and organize data where each value is associated with a unique key.

- **Keys**: Must be unique and immutable (e.g., strings, numbers, or tuples).  
- **Values**: Can be of any data type (e.g., strings, lists, numbers, or other dictionaries).  

Dictionaries are defined using **curly braces `{}`**.

### **Basic Syntax**
```python
# Example dictionary
example_dict = {
    "key1": "value1",
    "key2": "value2"
}


In [25]:
# Dictionary to store star properties
stars = {
    "Sirius": {"type": "Main Sequence", "temperature": 9940, "distance_ly": 8.6},
    "Betelgeuse": {"type": "Red Supergiant", "temperature": 3500, "distance_ly": 642.5},
    "Vega": {"type": "Main Sequence", "temperature": 9602, "distance_ly": 25.3}
}

# Accessing data for Sirius
print("Sirius properties:")
print("Type:", stars["Sirius"]["type"])
print("Surface Temperature:", stars["Sirius"]["temperature"], "K")
print("Distance:", stars["Sirius"]["distance_ly"], "light-years")


Sirius properties:
Type: Main Sequence
Surface Temperature: 9940 K
Distance: 8.6 light-years


In [26]:
stars

{'Sirius': {'type': 'Main Sequence', 'temperature': 9940, 'distance_ly': 8.6},
 'Betelgeuse': {'type': 'Red Supergiant',
  'temperature': 3500,
  'distance_ly': 642.5},
 'Vega': {'type': 'Main Sequence', 'temperature': 9602, 'distance_ly': 25.3}}

In [27]:
stars['Sirius']

{'type': 'Main Sequence', 'temperature': 9940, 'distance_ly': 8.6}

In [28]:
for key,val in stars['Sirius'].items():
    print(f"{key} = {val}\n")

type = Main Sequence

temperature = 9940

distance_ly = 8.6



In [29]:
stars['Sirius'].values()

dict_values(['Main Sequence', 9940, 8.6])

In [30]:
stars['Sirius'].keys()

dict_keys(['type', 'temperature', 'distance_ly'])

## Sets

Set is an unordered collection of unique elements. Unlike lists or tuples, sets do not allow duplicate values. They are useful when you need to store a collection of items without duplicates and perform mathematical set operations like union, intersection and difference.

** Key Characteristics of Sets **

1. Unordered - Sets do not maintain the order of elements.
2. Unique elements - Duplicate elements are automatically removed.
3. Mutable - You can add or remove elements.

In [84]:
# Creating a set
my_set = {1, 2, 3, 4}
print("Set:", my_set)

# Creating an empty set
empty_set = set()  # Use the set() constructor
print("Empty Set:", empty_set)


Set: {1, 2, 3, 4}
Empty Set: set()


In [85]:
# Adding elements
my_set.add(5)
print("After Adding 5:", my_set)

# Removing elements
my_set.remove(3)
print("After Removing 3:", my_set)

# Using discard (does not raise an error if the element is not found)
my_set.discard(10)  # No error
print("After Discarding 10:", my_set)


After Adding 5: {1, 2, 3, 4, 5}
After Removing 3: {1, 2, 4, 5}
After Discarding 10: {1, 2, 4, 5}


In [86]:
# Define two sets
set_a = {1, 2, 3, 4}
set_b = {3, 4, 5, 6}

# Union
print("Union:", set_a | set_b)  # or set_a.union(set_b)

# Intersection
print("Intersection:", set_a & set_b)  # or set_a.intersection(set_b)

# Difference
print("Difference (set_a - set_b):", set_a - set_b)

# Symmetric Difference
print("Symmetric Difference:", set_a ^ set_b)


Union: {1, 2, 3, 4, 5, 6}
Intersection: {3, 4}
Difference (set_a - set_b): {1, 2}
Symmetric Difference: {1, 2, 5, 6}


In [87]:
# Checking Membership

print(2 in set_a)  # True
print(7 not in set_a)  # True


True
True


In [88]:
# Removing duplicate elements

my_list = [1, 2, 2, 3, 4, 4, 5]
unique_elements = set(my_list)
print("Unique Elements:", unique_elements)


Unique Elements: {1, 2, 3, 4, 5}


In [89]:
set_a = {1, 2, 3}
set_b = {1, 2}

print("set_b is a subset of set_a:", set_b.issubset(set_a))
print("set_a is a superset of set_b:", set_a.issuperset(set_b))


set_b is a subset of set_a: True
set_a is a superset of set_b: True


In [2]:
large_list = list(range(1000000))
large_set = set(large_list)

# Membership test
import time

start_time = time.time()
print(999999 in large_list)  # Testing with a list
print("List Time:", time.time() - start_time)

start_time = time.time()
print(999999 in large_set)  # Testing with a set
print("Set Time:", time.time() - start_time)


True
List Time: 0.011547088623046875
True
Set Time: 7.796287536621094e-05


## Lists
- Lists is an ordered collection of elements enclosed within `[ ]`
- Lists are similar to tuples, the difference is that lists are $mutable$, i.e., we can change data or reassign items.
- `L = [1,2,'a','b',True,3.145,False]`
- Accessing elements is same as tuples.

    `L[0]`, `L[3]`, `L[2,6]`, etc

- To change the element in list enter the element number in square bracket and reassign 

    `L[0] = 100`
    
- To add element in list we use 'append',

    `L.append( )`
    
- To add list inside list,

    `L.append([5,6,7,8])`
    
- To remove element from list,

    `L.pop( )` - pops out the last element in list  
    `L.pop(index)` - pops out the element at the said index

In [31]:
# Define a list using [ ] square brackets
L = [1,2,'a','b',True,3.145,1+2j]

In [32]:
# Access elements using their index
L[4]

True

In [33]:
# Changing element in list
L[0] = 100
print(L)

[100, 2, 'a', 'b', True, 3.145, (1+2j)]


In [34]:
# Adding element in a list
L.append(24)
print(L)

[100, 2, 'a', 'b', True, 3.145, (1+2j), 24]


In [35]:
# Adding a list to a list
L.append([5,6,7,8])
print(L)

[100, 2, 'a', 'b', True, 3.145, (1+2j), 24, [5, 6, 7, 8]]


In [36]:
# Removing elements 
L.pop() # Will remove the last element
print(L)

[100, 2, 'a', 'b', True, 3.145, (1+2j), 24]


In [37]:
L.pop(3) # Will remove element at 3rd index i.e 'b'
print(L)

[100, 2, 'a', True, 3.145, (1+2j), 24]


### List Comprehension

List comprehensions provide a concise way to create lists in Python. They are especially useful for filtering and transforming data.

Syntax - `[expression for item in iterable if condition]`

In [7]:
numbers = [1,2,3,4,5,6,7,8,9,10]

In [10]:
even_squares = []
for n in numbers:
    if n%2==0:
        even_squares.append(n**2)
    else:
        even_squares.append(n)
even_squares

[1, 4, 3, 16, 5, 36, 7, 64, 9, 100]

In [13]:
squares = [n**2 for n in numbers]
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [14]:
even_squares = [n**2 for n in numbers if n%2==0]
even_squares

[4, 16, 36, 64, 100]

In [16]:
squares = [n**2 if n%2==0 else n for n in numbers]
squares

[1, 4, 3, 16, 5, 36, 7, 64, 9, 100]

In [18]:
# if there is if else condition in list comprehension then the if else conditions comes before the iterable condition
[n**2 for n in numbers if n%2==0 else n]

SyntaxError: invalid syntax (2270881187.py, line 2)

## Control Flow
- Control Flow statements like loops and conditionals have blocks indicated by indentations. Any number of whitespaces is syntactically correct as long as it is consistent within a block. Typically `tab` is used for indentation which is equivalent to 4 spaces.
- Looping statements are used to repeat tasks. To iterate over a sequence of numbers, the built-in function `range()` can be used. It generates arithmetic progression.
- `while` loop can execute a set of statements as long as a condition is `True`
- `for` loop is used for iterating over a sequence (either list, tuple, dictionary, set or string)
- `break` is used to stop the loop even if the while condition is `True`
- `continue` is used to stop the current iteration, and continue to the next.


### if/elif/else
- An `if` statement checks for the given condition
- Notations for logical conditons:
  - `a==b` - Equals
  - `a != b` - Not equal
  - `a < b` - Less than
  - `a <= b` - Less than or equal to
  - `a > b` - Greater than
  - `a >= b` - Greater than or equal to
- `elif` means else if (if the previous conditions were not true, then try this condition)
- `else` is for any other condition which doesn't belong to previous conditions.

In [38]:
a = 4
if a<5:
    print(a,"is less than 5.")
elif a==5:
    print(a,"is equal to 5.")
else:
    print(a,"is greater than 5.")

4 is less than 5.


**User Input**

Python allows for user input.  
`input` keyword prompts the user to enter the value.



In [39]:
b = float(input("Enter the number: ")) # takes the number from user and defines b as a float.
if b < 10:
    print(b,"is less than 10.")
elif b==10:
    print(b,"is equal to 10.")
else:
    print(b,"is greater than 10.")

Enter the number:  5


5.0 is less than 10.


### for/range
With `for` loop we can iterate over a sequence or execute a set of statements, once for each item in list, tuple, set, etc.

In [40]:
# strings are sequence of characters
# Loop through each letter and print it 
for x in "Physics":
  print(x)

P
h
y
s
i
c
s


In [41]:
# range() returns a sequence of numbers, starting from 0 by default, and increments by 1 by default.
for x in range(10):
  print(x)

0
1
2
3
4
5
6
7
8
9


In [42]:
# range(inclusive, exclusive, step size) 
# range(0,10,2) will give 0,2,4,6,8
for i in range(0,10,2): 
    print(2**i,end='  ')
#This will print powers of 2 upto 2^8

1  4  16  64  256  

In [43]:
# Example
# Gives factorial of a number
f = 1
n = int(input("Enter the number: "))
for i in range(1,n+1): # index of range is n + 1 
  f = f*i
print(n,"! = ",f)

Enter the number:  5


5 ! =  120


### while/continue
- `while` loop executes a set of statements as long as a condition is true.
- `continue` stops the current iteration and continues with the next.

In [44]:
i = 0
while i < 10:
  i = i + 1
  print(i)
# Try changing the order of i = i + 1 and print command and notice the difference

1
2
3
4
5
6
7
8
9
10


In [45]:
i = 0
while i < 10:
  print(i)
  if i == 5:
    break # This will exit the loop when i is 5
  i = i + 1

0
1
2
3
4
5


In [46]:
i = 0
while i < 10:
  i = i + 1
  if i == 5:
    continue # When i is 5 it will skip that iteration and continue
  print(i)

1
2
3
4
6
7
8
9
10


## Functions
- Function is a block of code which performs a specific task.

- You can pass data, known as parameters, into a function.
- Codes should ideally be robust, efficient, easy to debug, and of course, self explanatory for someone else reading it. Functions are very important for acheiving all of the above, with utmost simplicity. Functions are also very useful if you want the same task to be performed repeatedly, with no changes, or maybe with minor modifications.
- In python a function is defined using the keyword `def`
- Useful [documentation](https://docs.python.org/3/tutorial/controlflow.html#defining-functions).

In [47]:
# Defining a function which takes radius as parameters and returns area of circle
import math 
def areacircle(r):
    area = math.pi*r**2
    print("The area of circle of radius",r,"units is",round(area,2),"sq.units")
#round(area,2) will round off the value of area to second decimal place
# math.pi and round are function in math library that's why we imported it before.

In [48]:
# This is how you call a function, enter the values of parameters defined in function.
# r is the parameter in this function.
areacircle(6) 

The area of circle of radius 6 units is 113.1 sq.units


# NumPy
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- NumPy is a python library, stands for Numerical Python
- Used for working with arrays. It is very useful in Numerical calculations - matrices, linear algebra, etc
- The array object in NumPy is called ndarray (n-dimensional array). Arrays are frequently used in data sciences, where speed and accuracy matters. It is similar to list but it is way faster than that.
- Elements in NumPy array cannot be heterogeneous like in lists. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
- NumPy library was written partially in Python, but most of the parts that require fast computation are written in C or C++.
- For detailed information you can go through the [official documentation](https://numpy.org/doc/stable/user/absolute_beginners.html#numpy-the-absolute-basics-for-beginners) 
- [Source code for NumPy](https://github.com/numpy/numpy)

In [49]:
# To import the library use
import numpy

In [50]:
# add keyword numpy before using
a = numpy.array([1,2,3,4,5]) # defines a as numpy object 
# array is enclosed in ([])

NumPy is imported under the alias using the keyword "as" - import numpy as np  
This shortens the keyword required in syntax, instead of numpy.array we can type np.array

In [51]:
import numpy as np
a = np.array([1,2,3,4,5])
b = [1,2,3,4,5]
print(a)
print(b)
print(type(a)) # shows the type
print(type(b))

[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
<class 'list'>


Notice the output of print(a), it is enclosed in square brackets like lists but not separated by commas like lists. Hence the output is a numpy array.

In [52]:
#Use Tuple to create numpy array
import numpy as np
a = np.array((1,2,3,4,5))
print(a)
print(type(a))
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method.

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in Array
A dimension in array is one level of array depth

- nested arrays: are arrays that have arrays as elements.

#### Check Number of Dimensions of array
*ndim* attribute returns an integer that tells us how many dimensions an array has

if a is defined as an array, to check the dimensions of a, the syntax is - a.ndim

### 0-D Arrays
- 0-D Arrays or scalars are elements in array, each value in array is 0-D array.

In [53]:
import numpy as np
a = np.array(9) # single element
print(a)
print(a.ndim) #prints the dimension of an array

9
0


### 1-D Arrays
An array that has 0D Arrays as its elements.

In [54]:
a = np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


### 2-D Arrays
An array that has 1-D elements is called a 2D array

Represents a matrix

Note: NumPy also has a submodule dedicated for matrix operations called numpy.mat (go through [documentation](https://numpy.org/doc/stable/reference/generated/numpy.mat.html))

In [55]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


### 3-D Arrays
An array of 2D arrays is called a 3D array.

In [56]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]])
print(a)
print(a.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]]
3


## Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

In [57]:
import numpy as np
a = np.array([1,2,3,4])
print(a[0]) # Remember! first element has 0 index in python

1


In [58]:
'''To access elements from 2-D arrays we can use comma separated integers representing 
the dimension and the index of the element.'''

a = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
#[1,2,3,4,5] = 0th dimension, [6,7,8,9,10] = 1st dimension

print(a[0,1]) # first index = 0 ->selects 1st array, second index = 1 ->selects second element of first array

2


In [59]:
print(a[1,3]) #syntax - a[dimension,element]

9


In [60]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a[0,1,1]) 
'''
first index = 0 -> Selects [[1,2,3],[4,5,6]]
second index = 1 -> Selects [4,5,6]
third index = 1 -> Selects 5
'''
print("Dimensions of a: ",a.ndim)

5
Dimensions of a:  3


In [61]:
a.shape


(2, 2, 3)

a has 2 elements `[[1,2,3],[4,5,6]]` & `[[7,8,9],[10,11,12]]`  
of which each has 2 elements `[1,2,3]` & `[4,5,6]` of 1st element; `[7,8,9]` & `[10,11,12]` of 2nd element  
of which each has 3 elements `1,2,3` .... and so on you get the point  
`a.shape` returns (2,2,3) which is the shape of an array  

## Slicing Arrays
Syntax [start_inclusive:end_exclusive]

also

[start:end:step]

Leaving start or end index blank will mean start from beginning and go till end respectively

In [62]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[1:5]) # From 1st index to 4th index

[2 3 4 5]


In [63]:
a[:5] # From beginning to 4th index

array([1, 2, 3, 4, 5])

In [64]:
a[5:]

array([6, 7, 8, 9])

In [65]:
a[2:6:2] # from index 2 to 5 in steps of 2

array([3, 5])

In [66]:
b = np.array([1,2,3,4,5,6,7])
c = np.array_split(b,3) # array_split(array,no. of splits)
print(c)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


## Random
NumPy has a function `random` which creates an array of given shape and populate it with random samples from a uniform distribution over `[0,1)` [Documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

In [67]:
# import random from numpy so that we don't have to write np.random.rand()
from numpy import random 
x = random.rand() #returns a random float between 0 and 1
x

0.5015475482295897

`random.randint(low, high=None, size=None, dtype=int)`  
Return random integers from low (inclusive) to high (exclusive).  

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).  
[Documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html#numpy-random-randint)

In [68]:
x = random.randint(100, size=(5)) #gives an array of 5 random integers between 0 and 100
x

array([85, 93, 30, 23, 37])

In [69]:
x = random.randint(100, size=(3,3)) # gives a 3 x 3 array
x

array([[43,  3, 97],
       [77,  8, 75],
       [ 0, 80, 55]])

In [70]:
x = random.choice([3,5,7,9]) # chooses a random value from given array
x

9

In [71]:
x = random.choice([3,5,7,9],size=(3,3)) # creates a 3 x 3 array by choosing values randomly from given array
x

array([[7, 9, 9],
       [3, 3, 7],
       [7, 5, 5]])

In [72]:
x = random.randint(100, size=(5))
y = np.random.shuffle(x)
print(x)
print(y)

[33 83 14 23 74]
None


In [73]:
x = random.randint(1000,size=(10)) # 10 random values between 0 and 1000
print(x) 
print(np.var(x)) # Variance
print(np.std(x)) # Standard Deviation
print(np.average(x)) # Average

[592 503 192 373 260 508 729 735 327 290]
33471.69000000001
182.95269880490972
450.9


`np.random.randn()` returns a sample(or samples) from the "Standard Normal" Distribution.  
If positive int_like arguments are provided, `randn` generates an array of shape (d0,d1,...,dn), filled with random floats sampled from a univariate "normal" (Gaussian) distribution of mean 0 and variance 1. A single float randomly sampled from the distribution is returned if no argument is provided.

In [74]:
x = np.random.randn(10)
x

array([-0.16719043,  0.05021605,  0.70661422, -0.28233358,  0.66195865,
       -0.04643299,  2.17296151, -0.26231237,  0.37163251,  0.12564469])

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.

In [75]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
random.shuffle(x) 
x 

array([ 3,  9,  1, 10,  2,  7,  8,  4,  5,  6])

## **Functions like np.arange, np.linspace are very useful:**

np.arange (read as 'a range') gives an array of numbers within a given range and stepsize

np.linspace gives an array of linearly spaced numbers

In [76]:
np.arange(0,10,3) # syntax - (inclusive_start, exclusive_stop, stepsize)
#This will give an array of values from 0 to 10 in steps of 3

array([0, 3, 6, 9])

In [77]:
np.arange(-np.pi, np.pi, 1) 

array([-3.14159265, -2.14159265, -1.14159265, -0.14159265,  0.85840735,
        1.85840735,  2.85840735])

In [78]:
np.linspace(-np.pi, np.pi, 7) # linearly spaced values - difference between 2 consecutive values not necessarily 1

array([-3.14159265, -2.0943951 , -1.04719755,  0.        ,  1.04719755,
        2.0943951 ,  3.14159265])

**Notice** the difference between `np.arange()` function and `np.linspace()` function:

`np.arange` function gives values which have same difference but doesn't include the last value, whereas `np.linspace` function first sets start and end value and divides the numbers linearly.

This changes the output of both of these function significantly. 

In the syntax of `np.arange` function the **last value denotes the difference between each element**. But in `np.linspace` function the **last value denotes the number of elements desired in the given range**, the difference between each element is determined accoridingly by the system.

In [79]:
np.linspace(0,np.pi,10) #syntax - (inclusive_start, INCLUSIVE_stop, Number of elements)

array([0.        , 0.34906585, 0.6981317 , 1.04719755, 1.3962634 ,
       1.74532925, 2.0943951 , 2.44346095, 2.7925268 , 3.14159265])

## Convert Degrees into Radians and Radians to Degrees
By default the values are in radians, but we can convert it into degrees and vice versa if required

$$180^\circ=\pi\;rad$$
$$\therefore 1\;rad=\Big(\frac{180}{\pi}\Big)^\circ$$

In [80]:
# Suppose we have array of values in degrees
import numpy as np
x = np.array([0,30,45,60,90,180,270,360])
radian = np.deg2rad(x)
print(radian)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265
 4.71238898 6.28318531]


In [81]:
degree = np.rad2deg(radian)
print(degree)

[  0.  30.  45.  60.  90. 180. 270. 360.]


In [82]:
y = np.array([np.pi/2, np.pi, 4*np.pi/3, 2*np.pi])
y_degree = np.rad2deg(y)
print(y_degree)

[ 90. 180. 240. 360.]


NumPy also has the function to find angles i.e inverse trig values

arcsin( ), arccos( ), arctan( )

In [83]:
x = np.arcsin(0.8)
x_deg = np.rad2deg(x)
print(x)
print(round(x_deg,2)) # round(x_deg,2) rounds off the value of x_deg to 2 decimal places

0.9272952180016123
53.13
